name: Ubuntu environment build

on:
  push:
    branches:
      - 'main'
      - 'stable'
      - 'beta'
      - 'release/**'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    name: Build and Test Ubuntu
    strategy:
      fail-fast: false
      matrix:
        version: ['ubuntu:22.04', 'ubuntu:24.04']
    runs-on: [runs-on,runner=8cpu-linux-x64,"image=ubuntu24-full-x64","run-id=${{ github.run_id }}"]
    container:
      image: ${{ matrix.version }}
    steps:

      - uses: actions/checkout@v4

      - name: Install Dependencies and Make Quick Check
        run: |
          ./Tools/setup/ubuntu.sh
          make quick_check
